### ISSUE TITLE
ClassPortraits TBC with Party

### ISSUE THREAD

**Issue by Macumbafeh** [Schaka/ClassPortraits#3]
Heyo !

Your SchakaPvPUI Addon seems to work fine. but this addon (ClassPartraits) have an issue when you are in a Party :
![image](https://user-images.githubusercontent.com/47739411/83761746-02695d00-a677-11ea-9e74-83c06c2fdd89.png)

**Comment by Schaka** [comment]
Just copy the one over from SchakaPvPUI. The addon should utilize the PORTRAIT_CHANGED event, but this code is absolute garbage. I'll remove it entirely next week or so.

**Comment by Macumbafeh** [comment]
This is what is did ! and worked ! ty !
